### ISSUE TITLE
If a record is both offering and requesting help it creates an error in Match Now

### ISSUE THREAD

**Issue by vingle** [systopia/de.systopia.mutualaid#16] opened 2020-03-31 22:53 UTC
Testing on 35 records - a couple were both offering and requesting and running Match Now created the error:

"CiviCRM_API3_Exception: "Matching failed: Duplicate Relationship". 

If the only new records are coming through the forms then this probably isn't an issue as there's no way to create both a request and an offer together in the same record (only via import or adminastrator config). 

But am guessing longer term there may be scenarios where the same person is both offering and requesting things.

**Comment by bjendres** [comment] 2020-04-02 14:21
duplicate of #18

**Closed as completed by bjendres** 2020-04-02 14:22 UTC
